import google.generativeai as genai
from fpdf import FPDF
import os
import random
from faker import Faker
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# --- 1. CONFIGURATION ---
GEMINI_API_KEY = "AIzaSyDARO5TBBaisSeshSINeH79YUDNRgea9K4"

# --- 2. MOCK DATABASE GENERATOR ---
fake = Faker()

def generate_mock_jobs(count=50):
    """
    Generates a list of realistic-looking job postings.
    """
    jobs = []
    # We force some specific tech keywords so matching works well
    tech_stack = [
        "Python, SQL, Django", "React, Node.js, CSS", 
        "Java, Spring Boot, AWS", "Data Analysis, Excel, Tableau",
        "Machine Learning, TensorFlow, PyTorch", "Project Management, Agile",
        "Marketing, SEO, Content Writing", "Cybersecurity, Linux, Network"
    ]
    
    titles = [
        "Software Engineer", "Data Scientist", "Product Manager", 
        "Frontend Developer", "Backend Developer", "Marketing Specialist",
        "System Administrator", "AI Researcher"
    ]

    for i in range(count):
        chosen_stack = random.choice(tech_stack)
        title = random.choice(titles)
        
        job = {
            "id": i,
            "title": title,
            "company": fake.company(),
            "location": f"{fake.city()}, {fake.country_code()}",
            "salary": f"${random.randint(60, 150)}k/year",
            "type": random.choice(["Full-Time", "Remote", "Contract"]),
            "description": f"We are looking for a {title}. Required skills: {chosen_stack}. {fake.bs()}. {fake.catch_phrase()}.",
            "url": "#"
        }
        jobs.append(job)
    return jobs

# Generate database once when app starts
JOB_DATABASE = generate_mock_jobs(100)

# --- 3. JOB SEARCH (FROM MOCK DB) ---
def fetch_jobs_from_db(user_skills):
    """
    Searches the Mock Database using Cosine Similarity (Math).
    """
    if not user_skills:
        return JOB_DATABASE[:5] 
    
    job_descriptions = [job['description'] for job in JOB_DATABASE]
    documents = [user_skills] + job_descriptions
    
    tfidf = TfidfVectorizer(stop_words='english')
    tfidf_matrix = tfidf.fit_transform(documents)
    
    cosine_sim = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:])
    
    results = []
    for idx, score in enumerate(cosine_sim[0]):
        if score > 0.05: # 5% match threshold
            job = JOB_DATABASE[idx].copy()
            job['score'] = round(score * 100, 1)
            results.append(job)
            
    results = sorted(results, key=lambda x: x['score'], reverse=True)
    return results[:15]

# --- 4. AI CAREER PREDICTOR (UPDATED MODEL) ---
def predict_career_with_ai(skills_list):
    if not GEMINI_API_KEY:
        return "⚠️ Gemini Key missing."
    
    try:
        genai.configure(api_key=GEMINI_API_KEY)
        # CHANGED: Used 'gemini-1.5-flash' to fix 404 error
        model = genai.GenerativeModel('gemini-2.0-flash')
        
        skills_str = ", ".join(skills_list)
        prompt = f"I have these skills: {skills_str}. Based STRICTLY on these skills, what is the most specific job role title for me? Return ONLY the job title."
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        return f"AI Error: {str(e)}"

# --- 5. AI RESUME ENHANCER (UPDATED MODEL) ---
def refine_resume_with_ai(current_text):
    if not GEMINI_API_KEY:
        return "⚠️ Gemini Key missing."
    
    try:
        genai.configure(api_key=GEMINI_API_KEY)
        # CHANGED: Used 'gemini-1.5-flash' to fix 404 error
        model = genai.GenerativeModel('gemini-1.5-flash')
        
        prompt = f"Rewrite this resume bullet point using the STAR method to be professional: '{current_text}'"
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"Error: {str(e)}"

# --- 6. PDF GENERATION ---
class PDF(FPDF):
    def header(self): pass
    def footer(self): 
        self.set_y(-15); self.set_font('Arial', 'I', 8); self.set_text_color(128)
        self.cell(0, 10, 'Generated by AI Career Agent', 0, 0, 'C')

def create_pdf(name, email, phone, linkedin, role, summary, skills, experience, education, image_path=None):
    pdf = PDF()
    pdf.add_page()
    pdf.set_fill_color(32, 44, 57); pdf.rect(0, 0, 65, 297, 'F')
    
    if image_path and os.path.exists(image_path): 
        pdf.image(image_path, x=12.5, y=20, w=40)
    else: 
        pdf.set_y(30); pdf.set_font('Arial', 'B', 20); pdf.set_text_color(255,255,255); pdf.cell(65, 10, name[0] if name else "?", 0, 1, 'C')

    pdf.set_y(80); pdf.set_x(10); pdf.set_font('Arial', 'B', 12); pdf.set_text_color(255,255,255); pdf.cell(45, 10, "SKILLS", 0, 1, 'L'); pdf.line(10, 89, 55, 89)
    pdf.set_font('Arial', '', 10); pdf.set_y(95)
    for s in skills: pdf.set_x(10); pdf.cell(45, 6, f"- {s}", 0, 1, 'L')
    
    pdf.set_y(150); pdf.set_x(10); pdf.set_font('Arial', 'B', 12); pdf.cell(45, 10, "CONTACT", 0, 1, 'L'); pdf.line(10, 159, 55, 159)
    pdf.set_font('Arial', '', 9); pdf.set_y(165); pdf.set_x(10); pdf.multi_cell(45, 5, f"{phone}\n{email}\n{linkedin}")

    pdf.set_text_color(40, 40, 40); pdf.set_xy(75, 20); pdf.set_font('Arial', 'B', 24); pdf.cell(100, 10, name.upper(), 0, 1, 'L')
    pdf.set_xy(75, 30); pdf.set_font('Arial', 'I', 14); pdf.set_text_color(52, 152, 219); pdf.cell(100, 10, role, 0, 1, 'L'); pdf.set_text_color(40, 40, 40)
    
    def add_sec(title, body, off=0):
        y = pdf.get_y() + 10 + off; pdf.set_xy(75, y); pdf.set_font('Arial', 'B', 12); pdf.cell(0, 10, title, 0, 1, 'L'); pdf.line(75, y+9, 200, y+9)
        pdf.set_xy(75, y+12); pdf.set_font('Arial', '', 10); pdf.multi_cell(0, 5, body)
    
    add_sec("SUMMARY", summary, 20); add_sec("EXPERIENCE", experience); add_sec("EDUCATION", education)
    return pdf.output(dest='S').encode('latin-1')